build-arm64-apple-darwin25.5.0-arm-none-eabi-release-lib-static/src_select_format_list_style.o: \
 src/select/format_list_style.c \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/propget.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/computed.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/libwapcaplet/libwapcaplet.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/errors.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/functypes.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/types.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/fpmath.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/properties.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/unit.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/computed.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/hint.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/autogenerated_computed.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/autogenerated_propget.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/utils/utils.h
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/propget.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/computed.h:
/Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/libwapcaplet/libwapcaplet.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/errors.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/functypes.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/types.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/fpmath.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/properties.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/unit.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/computed.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/hint.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/autogenerated_computed.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/autogenerated_propget.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/utils/utils.h:
