build-arm64-apple-darwin25.5.0-arm-none-eabi-release-lib-static/src_select_properties_volume.o: \
 src/select/properties/volume.c \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/bytecode/bytecode.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/types.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/libwapcaplet/libwapcaplet.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/fpmath.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/properties.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/bytecode/opcodes.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/propset.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/computed.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/errors.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/functypes.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/unit.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/computed.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/hint.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/autogenerated_computed.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/autogenerated_propset.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/propget.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/autogenerated_propget.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/utils/utils.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/properties/properties.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/stylesheet.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/stylesheet.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/bytecode/bytecode.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/parse/parse.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/utils/vector.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/errors.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/functypes.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/types.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/parse/mq.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/parse/language.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/utils/stack.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/lex/lex.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/input/inputstream.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/charset/utf8.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/utils/buffer.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/parse/parse.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/parse/propstrings.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/hash.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/bloom.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/strings.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/select.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/select.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/properties/helpers.h \
 /Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/helpers.h
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/bytecode/bytecode.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/types.h:
/Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/libwapcaplet/libwapcaplet.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/fpmath.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/properties.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/bytecode/opcodes.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/propset.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/computed.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/errors.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/functypes.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/unit.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/computed.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/hint.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/autogenerated_computed.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/autogenerated_propset.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/propget.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/autogenerated_propget.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/utils/utils.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/properties/properties.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/stylesheet.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/stylesheet.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/bytecode/bytecode.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/parse/parse.h:
/Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/utils/vector.h:
/Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/errors.h:
/Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/functypes.h:
/Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/types.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/parse/mq.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/parse/language.h:
/Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/utils/stack.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/lex/lex.h:
/Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/input/inputstream.h:
/Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/charset/utf8.h:
/Users/tamino/Code/N3DS/netsurf-3ds/inst-framebuffer/include/parserutils/utils/buffer.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/parse/parse.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/parse/propstrings.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/hash.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/bloom.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/strings.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/select.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/include/libcss/select.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/properties/helpers.h:
/Users/tamino/Code/N3DS/netsurf-3ds/libcss/src/select/helpers.h:
